### ISSUE TITLE
Doc Bug: Building the Code · PX4 Developer Guide

### ISSUE THREAD

**Issue by shawn166888** [PX4/PX4-Devguide#439]
DESCRIBE PROBLEM WITH DOCS HERE

Bug Page: [Building the Code · PX4 Developer Guide](https://dev.px4.io/en/setup/building_px4.html)

Raspberry Pi 2/3 Boards
 --> Native Build
    -->sudo ./build/posix_rpi_native/src/firmware/posix/px4 ./posix-configs/rpi/px4.config
looks like executable is located in ./build/posix_rpi_native/px4

**Comment by hamishwillee** [comment]
Thanks for posting. 

If you read the preceding line it states:

> The "px4" executable file is in the directory build/posix_rpi_native/src/firmware/posix.

This does not stand out particularly, so I have changed it to bold: https://github.com/PX4/Devguide/commit/d513e514dbb4392ce71bee8d574a9d5459e2e844

In addition, sudo is always followed by a command rather than a folder so the trailing px4 must be an exe. 

I'm closing this, but if you have any further suggestions please reopen.
