### ISSUE TITLE
[Feature Request] Guide to Adding Params

### ISSUE THREAD

**Issue by mago3421** [PX4/PX4-Devguide#532]
Hi PX4-devs,

Could you please add a guide to adding custom parameters within PX4?

From the parameter and configs page, the most I can intuit is that I can add new parameters in each module's or driver's *_params.c file (including meta data) using the format below.

![image](https://user-images.githubusercontent.com/19937941/41204837-ff078e5e-6ca6-11e8-957e-c6c458e35c2f.png)

Can the team confirm this? Could it please be added to the dev guide?

Thanks! - Marc

**Comment by hamishwillee** [comment]
@mago3421 Params docs are here: https://dev.px4.io/en/advanced/parameters_and_configurations.html#parameter-meta-data

@bkueng I know you recently played with parameters. 
- Did you change anything that would affect https://dev.px4.io/en/advanced/parameters_and_configurations.html ?
- That document does not cover where you create parameters (ie at module level or some other level, the name of the file, the file location, how it is linked into the build toolchain, how a common parameter is shared between different modules.). 
- Can you expand on this, either here and I will add to above doc or document this?
- Perhaps we should also add example in https://dev.px4.io/en/apps/module_template.html ?

**Comment by bkueng** [comment]
> Did you change anything that would affect https://dev.px4.io/en/advanced/parameters_and_configurations.html ?

No, but I see 2 things:
- Right after the `param load /fs/microsd/vtol_param_backup` example, there should be a `param save`, because `load` will not save them. It assumes they are already saved, whereas the `import` will save them.
- There should be an example `param show -c` - it shows all changed parameters.

> That document does not cover where you create parameters (ie at module level or some other level, the name of the file, the file location, how it is linked into the build toolchain, how a common parameter is shared between different modules.).

- The file can be created anywhere under a module, it will be picked up by the build system if the module is added to the cmake target.
- You can then use the parameter from any module

> Perhaps we should also add example in https://dev.px4.io/en/apps/module_template.html ?

The module template contains a parameter example. I did not want to copy-paste code there on purpose. If you think we should add that, I'm ok with it.
