### ISSUE TITLE
Supported simulation setups

### ISSUE THREAD

**Issue by lamping7** [PX4/PX4-Devguide#569]
I'm not sure if this is in multiple places and should be removed from https://dev.px4.io/en/simulation/multi-vehicle-simulation.html or if this page needs updated now that newer/untested versions are out. See https://github.com/PX4/Firmware/issues/10088

**Comment by hamishwillee** [comment]
@lamping7 I believe this page is correct/up to date and that it has value. However there are new (? and better?) ways to do this. Not yet part of firmware, but we really need to get this into our docs (or linked) somehow: https://github.com/acsl-mipt/multiple-sitl/issues/5 (linked from https://github.com/PX4/Devguide/issues/384 )

I do not have time / my priorities have changed.

**Comment by lamping7** [comment]
I think the issue is that it says: ROS indigo or higher. The higher is the problem as we don't use or test the highest version. We also don't talk about the OS. We just say Linux.

**Comment by hamishwillee** [comment]
Thank you. I have changed in a couple of places to specify our standard build environment:
- https://github.com/PX4/Devguide/commit/1d09d1067e8be409f5b5f9f0c60c106a160a57fb
- https://github.com/PX4/Devguide/commit/52a02e9d9ab8b94eb987ff3be91a717db1ed7fcd 

I probably need to put some more thought into this, because our docs assume you come into the Linux story here: https://dev.px4.io/en/setup/dev_env_linux.html - this is the only place the version is mentioned and only up the top. On the other hand, in theory things should work on other versions of Ubuntu and Linux, we just don't test on them. 

So not sure how to fix this. It might be worth creating a variable in the book.json for this gitbook for current tested version, then sprinkling that through the docs. At least then version could be kept updated more consistently.

Anyway, I think this issue is sorted for now - ok?

**Comment by lamping7** [comment]
LGTM
