### ISSUE TITLE
Video streaming tutorial needs update

### ISSUE THREAD

**Issue by jinger26** [PX4/PX4-Devguide#666]
Page: https://dev.px4.io/en/qgc/video_streaming.html

The links in this guide are broken. Original content hosted on pixhawk.org. Due to site update, now reference links do not work anymore. 

Is the actual content still relevant or does it also need to be updated with new hardware selection/spec?

**Comment by hamishwillee** [comment]
I think this content should be deleted because it is no longer the way we would recommend, and is not even really a PX4 topic.

What it shows is  how you can connect a camera to an a companion computer (odroid), and then video stream the content to to QGC. 
However now we'd recommend the [Camera Manager](https://camera-manager.dronecode.org/en/) which does most of this work for you and is not specific to particular hardware, just support for a particular API on the device.

@lbegani @bkueng Does it make sense perhaps to delete the existing content here? If we do keep it, is it worth providing a link to https://camera-manager.dronecode.org/en/test/manual_tests.html#video-streaming

@lbegani As an aside, we probably need to highlight that information about setting up QGC to talk to the server in https://camera-manager.dronecode.org/en/test/manual_tests.html#video-streaming

**Comment by bkueng** [comment]
I thinkg the GStreamer section is the only part worth keeping, as it's generic and applies to other cameras as well.

**Comment by hamishwillee** [comment]
@bkueng I'm (slowly) going through and closing, migrating or fixing Devguide issues.
This one applies to [this article on the PX4 user guide](https://docs.px4.io/master/en/tutorials/video_streaming.html#gstreamer-installation)

Above (https://github.com/PX4/PX4-Devguide/issues/666#issuecomment-442351308) you said "the GStreamer section is the only part worth keeping, as it's generic and applies to other cameras as well." 

Were you thinking just renaming this "Gstreamer Installation on QGC/Companion" and replacing the term "Odroid" with something like "the companion computer running the Linux"?

**Comment by bkueng** [comment]
> Were you thinking just renaming this "Gstreamer Installation on QGC/Companion" and replacing the term "Odroid" with something like "the companion computer running the Linux"?

Yes. Or move it directly to QGC video docs (if that exists).
