### ISSUE TITLE
First Application Tutorial - Broken Link to px4_add_module () doc is broken

### ISSUE THREAD

**Issue by malife** [PX4/PX4-Devguide#796]
The [First Application Tutorial (Hello Sky)](https://dev.px4.io/en/apps/hello_sky.html) page, right before section  [Build the Application/Firmware](https://dev.px4.io/en/apps/hello_sky.html#build-the-applicationfirmware) there is a green tip box that reads:

> "The px4_add_module() format is documented in Firmware/cmake/common/px4_base.cmake"

The folder structure has changed as px4_base.cmake is now located under Firmware/cmake directly. Hence, when one clicks the link to follow to the github repo, you get a 404.

**Comment by hamishwillee** [comment]
Thanks very much. This was fixed in the head rev docs but not the older version. As per policy, except for very serious defects in docs I don't try and backport fixes. I think v1.9 will be out very soon, and that will fix this issue!

Thanks very much for reporting this though. It is helpful because I've also updated the head revision so that by default it will point to the file version associated with the release.
